name: Worlds
version: '1.0.0-SNAPSHOT'
main: dev.mending.worlds.Worlds
api-version: '1.21'
authors: [ MrMending ]
website: https://mending.dev
description: "Fast, simple and flexible World-Management System"
dependencies:
  server:
    MendingCore:
      required: true
      load: BEFORE